function CI = getRhoConfidenceIntervals(alpha_est,...
                                        rho_est,...
                                        sigma_rho_est, ...
                                        X, ...
                                        P, ...
                                        w, ...
                                        mixture_component), ...
            num_mixture_components = size(rho_est,1);
            FI_est = louisFisherEst(...
                                    alpha_est,...
                                    rho_est,...
                                    sigma_rho_est, ...
                                    X, ...
                                    P, ...
                                    w);
            rho_FI_est = FI_est(max(1,num_mixture_components-1):end,...
                    max(1,num_mixture_components-1):end); % only rho part
            a = .05; % TODO make this a variable
            std_err = vecLInverse(sqrt(abs(diag(pinv(rho_FI_est)))));
            %disp(std_err');
            j=1;
            z = norminv(1-a/2);
            actual_est = vecLInverse(rho_est{mixture_component});
            CI_upper = actual_est + z*std_err;
            CI_lower = actual_est - z*std_err;
            CI = {CI_lower CI_upper};
            %disp(CI)